default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push
  - post-checkout
  - post-merge

default_stages:
  - pre-commit

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        exclude: "tests/data/.+"
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: check-toml
      - id: detect-private-key

  - repo: https://github.com/pdm-project/pdm
    rev: 2.14.0
    hooks:
      - id: pdm-lock-check
      - id: pdm-sync

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        additional_dependencies:
          - emotional

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.2
    hooks:
      - id: check-github-workflows
      - id: check-dependabot

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        exclude: docs/.*\.pyi?$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli
      args: ["--write-changes"]
      exclude: CHANGELOG\.md
